Home work
anuvindhs/TechWithAnuvindh pull request #5
Opened 2024-12-16 08:02 UTC by leeit2024

Hi , i have done the home work request.
1. Create Day 1 folder under 03 Lee folder with new folder Assests  + README.MD with the what I learnt of the day 
2.  Create Day 2 folder under 03 Lee folder with new folder Assests  + README.MD with the what I learnt of the day 
3. Create Assests and README.md (Profile with picture) under 03 Lee folder .

Please Check.Thanks :)

2024-12-17 04:56 UTC, anuvindhs requested changes
remove PII

2024-12-19 00:19 UTC, leeit2024 commented
Remove PPI and update information

2025-01-05 08:14 UTC, amitcharan7 commented on Ninjas/MasterClass-03Lee/LearningHours.md
@leeit2024 Thank you for updating the learning hours :)

2025-01-05 08:21 UTC, amitcharan7 commented on Ninjas/MasterClass-03Lee/Day 3/README.md
@leeit2024 checked images have been moved to the asset folder.

2025-01-06 00:40 UTC, amitcharan7 commented on Ninjas/MasterClass-03Lee/Day 3/Assets/Clone Github website.png
@leeit2024 checked default index file has been changed to a custom index file.

2025-02-13 07:19 UTC, anuvindhs approved these changes

2025-02-13 07:19 UTC, merged