Updated Day 1, 2, 3 tasks
anuvindhs/TechWithAnuvindh pull request #6
Opened 2024-12-16 21:14 UTC by norvicweb1981

2024-12-17 04:56 UTC, anuvindhs requested changes
Remove PII

2024-12-27 23:30 UTC, norvicweb1981 commented
Day 03 Update

2024-12-27 23:32 UTC, norvicweb1981 reviewed
Day 03 tasks

2025-02-13 07:14 UTC, anuvindhs approved these changes

2025-02-13 07:14 UTC, anuvindhs commented on Ninjas/Masterclass-05Norvic/Day 01/Assets/GitbashSCSSHkeyauthenticatedA.PNG
your private is in the screenshot

2025-02-13 07:14 UTC, anuvindhs commented on Ninjas/Masterclass-05Norvic/Day 02/Assets/Pull request.png
what is this screenshot for ? heading and screenshot does not match

2025-02-13 07:14 UTC, merged