Lin 's homwork
anuvindhs/TechWithAnuvindh pull request #7
Opened 2024-12-16 21:18 UTC by rebeccazhang1216

Day1 
Day2
Profile with pic

2024-12-17 04:55 UTC, anuvindhs requested changes
remove PII

2024-12-26 07:26 UTC, rebeccazhang1216 reviewed
Review changes

2024-12-26 07:31 UTC, rebeccazhang1216 commented
HI Anuvindhs,
I have done my 3rd homework  ,and try to pull request here ,not sure if it successful. 
Please kindly let me know if anything wrong here.
Regards 

Lin

2025-01-06 05:47 UTC, anuvindhs submitted a review, later dismissed

2025-01-06 05:47 UTC, anuvindhs commented on Ninjas/MasterClass-02lin/Day 02/README.md
update day 2 learning

2025-01-06 05:47 UTC, anuvindhs commented on Ninjas/MasterClass-02lin/LearningHours.md
add meeting hours as well

2025-02-13 07:24 UTC, anuvindhs approved these changes

2025-02-13 07:29 UTC, merged