Created pages for 04 Amit
anuvindhs/TechWithAnuvindh pull request #8
Opened 2024-12-16 23:21 UTC by amitcharan7

Created pages:
- Day 1
- Day 2
- Activity Log
- Profile
Images in assets for each README.

2024-12-17 04:55 UTC, anuvindhs requested changes

2024-12-17 04:55 UTC, anuvindhs commented on Ninjas/MasterClass-04Amit/Day 1/README.md
remove PII

2024-12-17 05:02 UTC, amitcharan7 commented on Ninjas/MasterClass-04Amit/Day 1/README.md
Thank you. I have removed the PII as requested.

2025-01-05 08:10 UTC, leeit2024 commented on Ninjas/MasterClass-04Amit/Day 2/README.md
Checked the change.

2025-01-05 08:32 UTC, leeit2024 reviewed
Checked and all done .

2025-01-06 05:27 UTC, anuvindhs requested changes

2025-01-06 05:27 UTC, anuvindhs commented on Ninjas/MasterClass-04Amit/Day 2/README.md
> +### **3. Adding Octopus Plugin**
haha nice reference :), its called Markdown Preview Github Styling. Please update this

2025-01-06 05:29 UTC, anuvindhs approved these changes
review complete

2025-01-06 05:30 UTC, merged